@startuml packages_archility
set namespaceSeparator none
top to bottom direction
skinparam componentStyle rectangle
rectangle "conftest\n1 python file" as conftest
rectangle "src.archility\n0 child pkg, 5 modules\n6 python files\nexamples: __main__, audit, cli" as src.archility
rectangle "src.archility.__main__\n1 python file" as src.archility.__main__
rectangle "src.archility.audit\n1 python file" as src.archility.audit
rectangle "src.archility.cli\n1 python file" as src.archility.cli
rectangle "src.archility.generate\n1 python file" as src.archility.generate
rectangle "src.archility.render\n1 python file" as src.archility.render
src.archility --> src.archility.audit
src.archility --> src.archility.generate
src.archility --> src.archility.render
src.archility.__main__ --> src.archility.cli
src.archility.cli --> src.archility.audit
src.archility.cli --> src.archility.generate
src.archility.cli --> src.archility.render
src.archility.generate --> src.archility.audit
src.archility.generate --> src.archility.render
src.archility.render --> src.archility.audit
@enduml
